### ISSUE TITLE
'srcf.controllib.jobs.ChangeSocietyAdmin object' has no attribute 'has_danger'

### ISSUE THREAD

**Issue by eleanor-clifford** [SRCF/srcf-python#22]
/admin/jobs/failed is currently 500ing. Here is the error:

```
  File "/societies/control/checkouts/live/control/webapp/../templates/admin/view_jobs.html", line 23, in <module>
    <tr class="{{ job.state }}{% if job.has_danger %} table-warning{% elif note_count[job.job_id] %} table-secondary{% endif %}">
jinja2.exceptions.UndefinedError: 'srcf.controllib.jobs.ChangeSocietyAdmin object' has no attribute 'has_danger'
```

I can't replicate this locally or see any reason why ChangeSocietyAdmin wouldn't have this attribute... (but I don't have a proper dev setup for control so my attempt to replicate wasn't very similar to the deployment)

**Comment by rsa33** [comment]
What a confusing exception, given `has_danger` definitely exists as a property -- the problem is it references another property `owner_has_danger`, which in turn references the `danger` attribute that doesn't exist on the new `Missing` placeholder object, and _that_ `AttributeError` gets swallowed:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/srcf/controllib/jobs.py", line 299, in <lambda>
    has_danger = property(lambda s: s.owner_has_danger or s.society_has_danger)
  File "/usr/lib/python3/dist-packages/srcf/controllib/jobs.py", line 298, in <lambda>
    society_has_danger = property(lambda s: s.society and s.society.danger)
AttributeError: 'Missing' object has no attribute 'danger'
```
